CREATE TABLE PROFESSOR(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOME VARCHAR(50),
	USUARIO VARCHAR(30),
	EMAIL VARCHAR(50),
	SENHA VARCHAR(50),
	ATIVO SMALLINT(1),
	UNIQUE(USUARIO),
  UNIQUE(EMAIL)
);

CREATE TABLE QUESTAO(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TIPO INTEGER,
	MODELO VARCHAR(50),
	DIFICULDADE INTEGER,
	RANGE_MIN INTEGER,
  RANGE_MAX INTEGER,
	UNIQUE(MODELO)
);

CREATE TABLE PROVA(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PROFESSOR INTEGER,
	TIPO INTEGER,
	DIFICULDADE INTEGER,
	QTD_QUESTOES INTEGER,
	FOREIGN KEY(PROFESSOR) REFERENCES PROFESSOR(ID)
);

CREATE TABLE RESOLUCOES(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	QTD_ACERTOS INTEGER,
	NOME_ALUNO VARCHAR(30),
	EMAIL_ALUNO VARCHAR(100),
	PROVA INTEGER,
	FOREIGN KEY(PROVA) REFERENCES PROVA(ID)
);

CREATE TABLE ACTIVATE(
  EMAIL VARCHAR(50),
  MD5 VARCHAR(50),
  UNIQUE(MD5)
);

INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1+2','1','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1+1+3','1','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1-2','1','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1-2-3','1','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1-2-2','1','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1+2-3','1','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1*2','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1*2*3','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1*2*2','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1/2','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1/2-1','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1/2+1','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1/2+2*1/3','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1/2-2*1/3','1','0','5');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1+2+3+4','2','0','20');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1-2+3-4','2','0','20');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','1+2-3-4','2','0','20');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1+(2+[3*1]+4)','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1+(2-[3*1]-4)','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1+(2+[3*{1*2}]-1-[4*{3*1}])','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1-(2-[3*{1*2}]+1+[4*{3*1}])','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1-4/2+3-3/1','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1+4/2+3+3/1','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1-(2*[4/2+{3/1}-1])','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1+(2*[4/2-{3/1}-1])','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','1-(2*[4/2-{3/1}+1])','2','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','(1+2)-(3+4)+(3+1)-(5+2)','3','0','50');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','(1+2)-[{3+4}+{3+2}]-(4+2)','3','0','50');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','(1+2)-[{3+4}+{{5+4}-{3+2}}-{3+1}]-(4+2)','3','0','50');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('1','(1+2)+[{3+4}+{{1+2}+{3+2}}+{3+1}]+(4+2)','3','0','50');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1-(1*2*3)+(1*2*4)-4','3','0','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1+(1*2*[3-4-2*{2-1}]-2*4)','3','0','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1-(1*2*[3+4+1*{2-1}]-2*4)','3','0','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('2','1+(1*2*[3-4-5*{2+1}]+2*4)','3','0','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','2-4/2+3-3/1','3','0','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','2+4/2+3+3/1','3','1','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','2-(2*[4/2+{3/1}-1])','3','1','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','2+(2*[4/2-{3/1}-1])','3','1','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('3','2-(2*[4/2-{3/1}+1])','3','1','15');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('4','1^2','3','0','10');
INSERT INTO QUESTAO(TIPO, MODELO, DIFICULDADE, RANGE_MIN, RANGE_MAX) VALUES('5','q(1)','3','10','100');
INSERT INTO PROFESSOR(NOME, USUARIO, SENHA) VALUES('TESTE', 'teste', '22e862cc85fbc2c2f67a499db837babb');
