CREATE TABLE PROFESSOR(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50),
	USUARIO VARCHAR(30),
	SENHA VARCHAR(50),
	PRIMARY KEY(ID),
	UNIQUE(USUARIO)
);

CREATE TABLE QUESTAO(
	ID INT NOT NULL AUTO_INCREMENT,
	TIPO INT,
	MODELO VARCHAR(30),
	DIFICULDADE INT,
	PRIMARY KEY(ID),
	UNIQUE(MODELO)
);

CREATE TABLE PROVA(
	ID INT NOT NULL AUTO_INCREMENT,
	PROFESSOR INT,
	TIPO INT,
	DIFICULDADE INT,
	QTD_QUESTOES INT,
	PRIMARY KEY(ID),
	FOREIGN KEY(PROFESSOR) REFERENCES PROFESSOR(ID)
);

CREATE TABLE RESOLUCOES(
	ID INT NOT NULL AUTO_INCREMENT,
	QTD_ACERTOS INT,
	NOME_ALUNO VARCHAR(30),
	EMAIL_ALUNO VARCHAR(100)
	PROVA INT,
	PRIMARY KEY(ID,EMAIL,PROVA), 
	FOREIGN KEY(PROVA) REFERENCES PROVA(ID)
);